/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Sergio Cruz
 */
public class ConsultarMazo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarMazo1
     */
    public ConsultarMazo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        pndC1 = new javax.swing.JPanel();
        lblC1 = new javax.swing.JLabel();
        Ctipo1 = new javax.swing.JTextField();
        Cnombre1 = new javax.swing.JTextField();
        Ccalidad1 = new javax.swing.JTextField();
        pndC2 = new javax.swing.JPanel();
        lblC2 = new javax.swing.JLabel();
        Ctipo2 = new javax.swing.JTextField();
        Cnombre2 = new javax.swing.JTextField();
        Ccalidad2 = new javax.swing.JTextField();
        pndC3 = new javax.swing.JPanel();
        lblC3 = new javax.swing.JLabel();
        Ccalidad3 = new javax.swing.JTextField();
        Ctipo3 = new javax.swing.JTextField();
        Cnombre3 = new javax.swing.JTextField();
        pndC4 = new javax.swing.JPanel();
        lblC4 = new javax.swing.JLabel();
        Ccalidad4 = new javax.swing.JTextField();
        Ctipo4 = new javax.swing.JTextField();
        Cnombre4 = new javax.swing.JTextField();
        pndC5 = new javax.swing.JPanel();
        lblC5 = new javax.swing.JLabel();
        Ccalidad5 = new javax.swing.JTextField();
        Ctipo5 = new javax.swing.JTextField();
        Cnombre5 = new javax.swing.JTextField();
        pndC6 = new javax.swing.JPanel();
        lblC6 = new javax.swing.JLabel();
        Ccalidad6 = new javax.swing.JTextField();
        Ctipo6 = new javax.swing.JTextField();
        Cnombre6 = new javax.swing.JTextField();
        pndC7 = new javax.swing.JPanel();
        lblC7 = new javax.swing.JLabel();
        Ccalidad7 = new javax.swing.JTextField();
        Ctipo7 = new javax.swing.JTextField();
        Cnombre7 = new javax.swing.JTextField();
        pndC8 = new javax.swing.JPanel();
        lblC8 = new javax.swing.JLabel();
        Ccalidad8 = new javax.swing.JTextField();
        Cnombre8 = new javax.swing.JTextField();
        Ctipo10 = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();

        lblTitulo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        lblTitulo.setText("Consulta de Mazos");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        pndC1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC1Layout = new javax.swing.GroupLayout(pndC1);
        pndC1.setLayout(pndC1Layout);
        pndC1Layout.setHorizontalGroup(
            pndC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC1Layout.setVerticalGroup(
            pndC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ctipo1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Cnombre1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Ccalidad1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        pndC2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC2Layout = new javax.swing.GroupLayout(pndC2);
        pndC2.setLayout(pndC2Layout);
        pndC2Layout.setHorizontalGroup(
            pndC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC2Layout.setVerticalGroup(
            pndC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ctipo2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Cnombre2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Ccalidad2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        pndC3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC3Layout = new javax.swing.GroupLayout(pndC3);
        pndC3.setLayout(pndC3Layout);
        pndC3Layout.setHorizontalGroup(
            pndC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC3Layout.setVerticalGroup(
            pndC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Ctipo3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Cnombre3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        pndC4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC4Layout = new javax.swing.GroupLayout(pndC4);
        pndC4.setLayout(pndC4Layout);
        pndC4Layout.setHorizontalGroup(
            pndC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC4Layout.setVerticalGroup(
            pndC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Ctipo4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Cnombre4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        pndC5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC5Layout = new javax.swing.GroupLayout(pndC5);
        pndC5.setLayout(pndC5Layout);
        pndC5Layout.setHorizontalGroup(
            pndC5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC5Layout.setVerticalGroup(
            pndC5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Ctipo5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Cnombre5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        pndC6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC6Layout = new javax.swing.GroupLayout(pndC6);
        pndC6.setLayout(pndC6Layout);
        pndC6Layout.setHorizontalGroup(
            pndC6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC6Layout.setVerticalGroup(
            pndC6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Ctipo6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Cnombre6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        pndC7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC7Layout = new javax.swing.GroupLayout(pndC7);
        pndC7.setLayout(pndC7Layout);
        pndC7Layout.setHorizontalGroup(
            pndC7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC7Layout.setVerticalGroup(
            pndC7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Ccalidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ccalidad7ActionPerformed(evt);
            }
        });

        Ctipo7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        Ctipo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ctipo7ActionPerformed(evt);
            }
        });

        Cnombre7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        pndC8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC8Layout = new javax.swing.GroupLayout(pndC8);
        pndC8.setLayout(pndC8Layout);
        pndC8Layout.setHorizontalGroup(
            pndC8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC8Layout.setVerticalGroup(
            pndC8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Cnombre8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        Ctipo10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N

        btnAnterior.setText("Anterior");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Ctipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ccalidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(pndC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Ctipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cnombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ccalidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(pndC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Ctipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ccalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(pndC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(90, 90, 90)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Ctipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Cnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Ccalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(pndC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ctipo7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cnombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ccalidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(pndC7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Cnombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ccalidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(45, 45, 45)
                                        .addComponent(Ctipo5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(pndC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ctipo6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cnombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ccalidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(pndC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Ctipo10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Cnombre8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Ccalidad8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(pndC8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(46, 46, 46)
                .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Ctipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(Cnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ccalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pndC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Ctipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(Cnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ccalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pndC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Ctipo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(Cnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ccalidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pndC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Ctipo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(Cnombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ccalidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pndC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ctipo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Cnombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ccalidad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pndC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Ctipo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAnterior))
                                .addGap(26, 26, 26)
                                .addComponent(Cnombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ccalidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pndC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSiguiente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Ctipo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(Cnombre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ccalidad7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pndC7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Ctipo10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(Cnombre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ccalidad8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(pndC8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void Ccalidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ccalidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ccalidad7ActionPerformed

    private void Ctipo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ctipo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ctipo7ActionPerformed

    public JTextField getCcalidad1() {
        return Ccalidad1;
    }

    public void setCcalidad1(JTextField Ccalidad1) {
        this.Ccalidad1 = Ccalidad1;
    }

    public JTextField getCcalidad2() {
        return Ccalidad2;
    }

    public void setCcalidad2(JTextField Ccalidad2) {
        this.Ccalidad2 = Ccalidad2;
    }

    public JTextField getCcalidad3() {
        return Ccalidad3;
    }

    public void setCcalidad3(JTextField Ccalidad3) {
        this.Ccalidad3 = Ccalidad3;
    }

    public JTextField getCcalidad4() {
        return Ccalidad4;
    }

    public void setCcalidad4(JTextField Ccalidad4) {
        this.Ccalidad4 = Ccalidad4;
    }

    public JTextField getCcalidad5() {
        return Ccalidad5;
    }

    public void setCcalidad5(JTextField Ccalidad5) {
        this.Ccalidad5 = Ccalidad5;
    }

    public JTextField getCcalidad6() {
        return Ccalidad6;
    }

    public void setCcalidad6(JTextField Ccalidad6) {
        this.Ccalidad6 = Ccalidad6;
    }

    public JTextField getCcalidad7() {
        return Ccalidad7;
    }

    public void setCcalidad7(JTextField Ccalidad7) {
        this.Ccalidad7 = Ccalidad7;
    }

    public JTextField getCcalidad8() {
        return Ccalidad8;
    }

    public void setCcalidad8(JTextField Ccalidad8) {
        this.Ccalidad8 = Ccalidad8;
    }

    public JTextField getCnombre1() {
        return Cnombre1;
    }

    public void setCnombre1(JTextField Cnombre1) {
        this.Cnombre1 = Cnombre1;
    }

    public JTextField getCnombre2() {
        return Cnombre2;
    }

    public void setCnombre2(JTextField Cnombre2) {
        this.Cnombre2 = Cnombre2;
    }

    public JTextField getCnombre3() {
        return Cnombre3;
    }

    public void setCnombre3(JTextField Cnombre3) {
        this.Cnombre3 = Cnombre3;
    }

    public JTextField getCnombre4() {
        return Cnombre4;
    }

    public void setCnombre4(JTextField Cnombre4) {
        this.Cnombre4 = Cnombre4;
    }

    public JTextField getCnombre5() {
        return Cnombre5;
    }

    public void setCnombre5(JTextField Cnombre5) {
        this.Cnombre5 = Cnombre5;
    }

    public JTextField getCnombre6() {
        return Cnombre6;
    }

    public void setCnombre6(JTextField Cnombre6) {
        this.Cnombre6 = Cnombre6;
    }

    public JTextField getCnombre7() {
        return Cnombre7;
    }

    public void setCnombre7(JTextField Cnombre7) {
        this.Cnombre7 = Cnombre7;
    }

    public JTextField getCnombre8() {
        return Cnombre8;
    }

    public void setCnombre8(JTextField Cnombre8) {
        this.Cnombre8 = Cnombre8;
    }

    public JTextField getCtipo1() {
        return Ctipo1;
    }

    public void setCtipo1(JTextField Ctipo1) {
        this.Ctipo1 = Ctipo1;
    }

    public JTextField getCtipo10() {
        return Ctipo10;
    }

    public void setCtipo10(JTextField Ctipo10) {
        this.Ctipo10 = Ctipo10;
    }

    public JTextField getCtipo2() {
        return Ctipo2;
    }

    public void setCtipo2(JTextField Ctipo2) {
        this.Ctipo2 = Ctipo2;
    }

    public JTextField getCtipo3() {
        return Ctipo3;
    }

    public void setCtipo3(JTextField Ctipo3) {
        this.Ctipo3 = Ctipo3;
    }

    public JTextField getCtipo4() {
        return Ctipo4;
    }

    public void setCtipo4(JTextField Ctipo4) {
        this.Ctipo4 = Ctipo4;
    }

    public JTextField getCtipo5() {
        return Ctipo5;
    }

    public void setCtipo5(JTextField Ctipo5) {
        this.Ctipo5 = Ctipo5;
    }

    public JTextField getCtipo6() {
        return Ctipo6;
    }

    public void setCtipo6(JTextField Ctipo6) {
        this.Ctipo6 = Ctipo6;
    }

    public JTextField getCtipo7() {
        return Ctipo7;
    }

    public void setCtipo7(JTextField Ctipo7) {
        this.Ctipo7 = Ctipo7;
    }

    public JButton getBtnAnterior() {
        return btnAnterior;
    }

    public void setBtnAnterior(JButton btnAnterior) {
        this.btnAnterior = btnAnterior;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JLabel getLblC1() {
        return lblC1;
    }

    public void setLblC1(JLabel lblC1) {
        this.lblC1 = lblC1;
    }

    public JLabel getLblC2() {
        return lblC2;
    }

    public void setLblC2(JLabel lblC2) {
        this.lblC2 = lblC2;
    }

    public JLabel getLblC3() {
        return lblC3;
    }

    public void setLblC3(JLabel lblC3) {
        this.lblC3 = lblC3;
    }

    public JLabel getLblC4() {
        return lblC4;
    }

    public void setLblC4(JLabel lblC4) {
        this.lblC4 = lblC4;
    }

    public JLabel getLblC5() {
        return lblC5;
    }

    public void setLblC5(JLabel lblC5) {
        this.lblC5 = lblC5;
    }

    public JLabel getLblC6() {
        return lblC6;
    }

    public void setLblC6(JLabel lblC6) {
        this.lblC6 = lblC6;
    }

    public JLabel getLblC7() {
        return lblC7;
    }

    public void setLblC7(JLabel lblC7) {
        this.lblC7 = lblC7;
    }

    public JLabel getLblC8() {
        return lblC8;
    }

    public void setLblC8(JLabel lblC8) {
        this.lblC8 = lblC8;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public JPanel getPndC1() {
        return pndC1;
    }

    public void setPndC1(JPanel pndC1) {
        this.pndC1 = pndC1;
    }

    public JPanel getPndC2() {
        return pndC2;
    }

    public void setPndC2(JPanel pndC2) {
        this.pndC2 = pndC2;
    }

    public JPanel getPndC3() {
        return pndC3;
    }

    public void setPndC3(JPanel pndC3) {
        this.pndC3 = pndC3;
    }

    public JPanel getPndC4() {
        return pndC4;
    }

    public void setPndC4(JPanel pndC4) {
        this.pndC4 = pndC4;
    }

    public JPanel getPndC5() {
        return pndC5;
    }

    public void setPndC5(JPanel pndC5) {
        this.pndC5 = pndC5;
    }

    public JPanel getPndC6() {
        return pndC6;
    }

    public void setPndC6(JPanel pndC6) {
        this.pndC6 = pndC6;
    }

    public JPanel getPndC7() {
        return pndC7;
    }

    public void setPndC7(JPanel pndC7) {
        this.pndC7 = pndC7;
    }

    public JPanel getPndC8() {
        return pndC8;
    }

    public void setPndC8(JPanel pndC8) {
        this.pndC8 = pndC8;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ccalidad1;
    private javax.swing.JTextField Ccalidad2;
    private javax.swing.JTextField Ccalidad3;
    private javax.swing.JTextField Ccalidad4;
    private javax.swing.JTextField Ccalidad5;
    private javax.swing.JTextField Ccalidad6;
    private javax.swing.JTextField Ccalidad7;
    private javax.swing.JTextField Ccalidad8;
    private javax.swing.JTextField Cnombre1;
    private javax.swing.JTextField Cnombre2;
    private javax.swing.JTextField Cnombre3;
    private javax.swing.JTextField Cnombre4;
    private javax.swing.JTextField Cnombre5;
    private javax.swing.JTextField Cnombre6;
    private javax.swing.JTextField Cnombre7;
    private javax.swing.JTextField Cnombre8;
    private javax.swing.JTextField Ctipo1;
    private javax.swing.JTextField Ctipo10;
    private javax.swing.JTextField Ctipo2;
    private javax.swing.JTextField Ctipo3;
    private javax.swing.JTextField Ctipo4;
    private javax.swing.JTextField Ctipo5;
    private javax.swing.JTextField Ctipo6;
    private javax.swing.JTextField Ctipo7;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC5;
    private javax.swing.JLabel lblC6;
    private javax.swing.JLabel lblC7;
    private javax.swing.JLabel lblC8;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pndC1;
    private javax.swing.JPanel pndC2;
    private javax.swing.JPanel pndC3;
    private javax.swing.JPanel pndC4;
    private javax.swing.JPanel pndC5;
    private javax.swing.JPanel pndC6;
    private javax.swing.JPanel pndC7;
    private javax.swing.JPanel pndC8;
    // End of variables declaration//GEN-END:variables
}
