/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JSeparator;
import javax.swing.JTextField;

/**
 *
 * @author Sergio Cruz
 */
public class ConsultarMazo extends javax.swing.JInternalFrame {

    /**
     * Creates new form ConsultarMazo1
     */
    public ConsultarMazo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        pndC1 = new javax.swing.JPanel();
        lblC1 = new javax.swing.JLabel();
        Ctipo1 = new javax.swing.JTextField();
        Cnombre1 = new javax.swing.JTextField();
        Ccalidad1 = new javax.swing.JTextField();
        pndC2 = new javax.swing.JPanel();
        lblC2 = new javax.swing.JLabel();
        Ctipo2 = new javax.swing.JTextField();
        Cnombre2 = new javax.swing.JTextField();
        Ccalidad2 = new javax.swing.JTextField();
        pndC3 = new javax.swing.JPanel();
        lblC3 = new javax.swing.JLabel();
        Ccalidad3 = new javax.swing.JTextField();
        Ctipo3 = new javax.swing.JTextField();
        Cnombre3 = new javax.swing.JTextField();
        pndC4 = new javax.swing.JPanel();
        lblC4 = new javax.swing.JLabel();
        Ccalidad4 = new javax.swing.JTextField();
        Ctipo4 = new javax.swing.JTextField();
        Cnombre4 = new javax.swing.JTextField();
        pndC5 = new javax.swing.JPanel();
        lblC5 = new javax.swing.JLabel();
        Ccalidad5 = new javax.swing.JTextField();
        Ctipo5 = new javax.swing.JTextField();
        Cnombre5 = new javax.swing.JTextField();
        pndC6 = new javax.swing.JPanel();
        lblC6 = new javax.swing.JLabel();
        Ccalidad6 = new javax.swing.JTextField();
        Ctipo6 = new javax.swing.JTextField();
        Cnombre6 = new javax.swing.JTextField();
        pndC7 = new javax.swing.JPanel();
        lblC7 = new javax.swing.JLabel();
        Ccalidad7 = new javax.swing.JTextField();
        Ctipo7 = new javax.swing.JTextField();
        Cnombre7 = new javax.swing.JTextField();
        pndC8 = new javax.swing.JPanel();
        lblC8 = new javax.swing.JLabel();
        Ccalidad8 = new javax.swing.JTextField();
        Cnombre8 = new javax.swing.JTextField();
        Ctipo8 = new javax.swing.JTextField();
        btnAnterior = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pgrBarUtilidad = new javax.swing.JProgressBar();
        lblUtilidad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        pgrBarVida = new javax.swing.JProgressBar();
        lblVida = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        pgrBarElixir = new javax.swing.JProgressBar();
        lblElixir = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lblTitulo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        lblTitulo.setText("Consulta de Mazos");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        pndC1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC1Layout = new javax.swing.GroupLayout(pndC1);
        pndC1.setLayout(pndC1Layout);
        pndC1Layout.setHorizontalGroup(
            pndC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC1Layout.setVerticalGroup(
            pndC1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ctipo1.setEditable(false);
        Ctipo1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ctipo1.setToolTipText("");

        Cnombre1.setEditable(false);
        Cnombre1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Cnombre1.setToolTipText("");

        Ccalidad1.setEditable(false);
        Ccalidad1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ccalidad1.setToolTipText("");

        pndC2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC2Layout = new javax.swing.GroupLayout(pndC2);
        pndC2.setLayout(pndC2Layout);
        pndC2Layout.setHorizontalGroup(
            pndC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC2Layout.setVerticalGroup(
            pndC2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ctipo2.setEditable(false);
        Ctipo2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ctipo2.setToolTipText("");

        Cnombre2.setEditable(false);
        Cnombre2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Cnombre2.setToolTipText("");

        Ccalidad2.setEditable(false);
        Ccalidad2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ccalidad2.setToolTipText("");
        Ccalidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ccalidad2ActionPerformed(evt);
            }
        });

        pndC3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC3Layout = new javax.swing.GroupLayout(pndC3);
        pndC3.setLayout(pndC3Layout);
        pndC3Layout.setHorizontalGroup(
            pndC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC3Layout.setVerticalGroup(
            pndC3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad3.setEditable(false);
        Ccalidad3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ccalidad3.setToolTipText("");

        Ctipo3.setEditable(false);
        Ctipo3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ctipo3.setToolTipText("");

        Cnombre3.setEditable(false);
        Cnombre3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Cnombre3.setToolTipText("");

        pndC4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC4Layout = new javax.swing.GroupLayout(pndC4);
        pndC4.setLayout(pndC4Layout);
        pndC4Layout.setHorizontalGroup(
            pndC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC4Layout.setVerticalGroup(
            pndC4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad4.setEditable(false);
        Ccalidad4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ccalidad4.setToolTipText("");

        Ctipo4.setEditable(false);
        Ctipo4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ctipo4.setToolTipText("");

        Cnombre4.setEditable(false);
        Cnombre4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Cnombre4.setToolTipText("");

        pndC5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC5Layout = new javax.swing.GroupLayout(pndC5);
        pndC5.setLayout(pndC5Layout);
        pndC5Layout.setHorizontalGroup(
            pndC5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC5Layout.setVerticalGroup(
            pndC5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad5.setEditable(false);
        Ccalidad5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ccalidad5.setToolTipText("");

        Ctipo5.setEditable(false);
        Ctipo5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ctipo5.setToolTipText("");

        Cnombre5.setEditable(false);
        Cnombre5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Cnombre5.setToolTipText("");

        pndC6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC6Layout = new javax.swing.GroupLayout(pndC6);
        pndC6.setLayout(pndC6Layout);
        pndC6Layout.setHorizontalGroup(
            pndC6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC6, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC6Layout.setVerticalGroup(
            pndC6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad6.setEditable(false);
        Ccalidad6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ccalidad6.setToolTipText("");

        Ctipo6.setEditable(false);
        Ctipo6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ctipo6.setToolTipText("");

        Cnombre6.setEditable(false);
        Cnombre6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Cnombre6.setToolTipText("");

        pndC7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC7Layout = new javax.swing.GroupLayout(pndC7);
        pndC7.setLayout(pndC7Layout);
        pndC7Layout.setHorizontalGroup(
            pndC7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC7, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC7Layout.setVerticalGroup(
            pndC7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad7.setEditable(false);
        Ccalidad7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ccalidad7.setToolTipText("");
        Ccalidad7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ccalidad7ActionPerformed(evt);
            }
        });

        Ctipo7.setEditable(false);
        Ctipo7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ctipo7.setToolTipText("");
        Ctipo7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ctipo7ActionPerformed(evt);
            }
        });

        Cnombre7.setEditable(false);
        Cnombre7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Cnombre7.setToolTipText("");

        pndC8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout pndC8Layout = new javax.swing.GroupLayout(pndC8);
        pndC8.setLayout(pndC8Layout);
        pndC8Layout.setHorizontalGroup(
            pndC8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC8, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pndC8Layout.setVerticalGroup(
            pndC8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblC8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Ccalidad8.setEditable(false);
        Ccalidad8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ccalidad8.setToolTipText("");

        Cnombre8.setEditable(false);
        Cnombre8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Cnombre8.setToolTipText("");

        Ctipo8.setEditable(false);
        Ctipo8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 11)); // NOI18N
        Ctipo8.setToolTipText("");

        btnAnterior.setText("Anterior");

        jLabel1.setText("Utilidad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(pgrBarUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgrBarUtilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel3.setText("Vida");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(pgrBarVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lblVida, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel3)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblVida, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgrBarVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel2.setText("Elixir");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(pgrBarElixir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblElixir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblElixir, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgrBarElixir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Cnombre5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ccalidad5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                                .addGap(45, 45, 45)
                                                .addComponent(Ctipo5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addComponent(pndC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Ctipo7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Cnombre7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ccalidad7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(pndC7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(90, 90, 90)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Ctipo6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Cnombre6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ccalidad6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(pndC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Ctipo8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Cnombre8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ccalidad8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(pndC8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Ctipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Cnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Ccalidad3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(pndC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(90, 90, 90)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Ctipo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Cnombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Ccalidad4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(pndC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Ctipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Cnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Ccalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(pndC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(90, 90, 90)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(Ctipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Cnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(Ccalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(18, 18, 18)
                                            .addComponent(pndC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addComponent(btnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pndC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pndC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ctipo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ccalidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ctipo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cnombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ccalidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pndC3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pndC4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ctipo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cnombre3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ccalidad3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ctipo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cnombre4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ccalidad4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Ctipo6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cnombre6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ccalidad6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pndC6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAnterior)
                                        .addGap(26, 26, 26))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Ctipo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(Cnombre5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ccalidad5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pndC5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnSiguiente))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pndC7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pndC8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ctipo7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cnombre7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ccalidad7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ctipo8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cnombre8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Ccalidad8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void Ccalidad7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ccalidad7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ccalidad7ActionPerformed

    private void Ctipo7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ctipo7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ctipo7ActionPerformed

    private void Ccalidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ccalidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ccalidad2ActionPerformed

    public JTextField getCcalidad1() {
        return Ccalidad1;
    }

    public void setCcalidad1(JTextField Ccalidad1) {
        this.Ccalidad1 = Ccalidad1;
    }

    public JTextField getCcalidad2() {
        return Ccalidad2;
    }

    public void setCcalidad2(JTextField Ccalidad2) {
        this.Ccalidad2 = Ccalidad2;
    }

    public JTextField getCcalidad3() {
        return Ccalidad3;
    }

    public void setCcalidad3(JTextField Ccalidad3) {
        this.Ccalidad3 = Ccalidad3;
    }

    public JTextField getCcalidad4() {
        return Ccalidad4;
    }

    public void setCcalidad4(JTextField Ccalidad4) {
        this.Ccalidad4 = Ccalidad4;
    }

    public JTextField getCcalidad5() {
        return Ccalidad5;
    }

    public void setCcalidad5(JTextField Ccalidad5) {
        this.Ccalidad5 = Ccalidad5;
    }

    public JTextField getCcalidad6() {
        return Ccalidad6;
    }

    public void setCcalidad6(JTextField Ccalidad6) {
        this.Ccalidad6 = Ccalidad6;
    }

    public JTextField getCcalidad7() {
        return Ccalidad7;
    }

    public void setCcalidad7(JTextField Ccalidad7) {
        this.Ccalidad7 = Ccalidad7;
    }

    public JTextField getCcalidad8() {
        return Ccalidad8;
    }

    public void setCcalidad8(JTextField Ccalidad8) {
        this.Ccalidad8 = Ccalidad8;
    }

    public JTextField getCnombre1() {
        return Cnombre1;
    }

    public void setCnombre1(JTextField Cnombre1) {
        this.Cnombre1 = Cnombre1;
    }

    public JTextField getCnombre2() {
        return Cnombre2;
    }

    public void setCnombre2(JTextField Cnombre2) {
        this.Cnombre2 = Cnombre2;
    }

    public JTextField getCnombre3() {
        return Cnombre3;
    }

    public void setCnombre3(JTextField Cnombre3) {
        this.Cnombre3 = Cnombre3;
    }

    public JTextField getCnombre4() {
        return Cnombre4;
    }

    public void setCnombre4(JTextField Cnombre4) {
        this.Cnombre4 = Cnombre4;
    }

    public JTextField getCnombre5() {
        return Cnombre5;
    }

    public void setCnombre5(JTextField Cnombre5) {
        this.Cnombre5 = Cnombre5;
    }

    public JTextField getCnombre6() {
        return Cnombre6;
    }

    public void setCnombre6(JTextField Cnombre6) {
        this.Cnombre6 = Cnombre6;
    }

    public JTextField getCnombre7() {
        return Cnombre7;
    }

    public void setCnombre7(JTextField Cnombre7) {
        this.Cnombre7 = Cnombre7;
    }

    public JTextField getCnombre8() {
        return Cnombre8;
    }

    public void setCnombre8(JTextField Cnombre8) {
        this.Cnombre8 = Cnombre8;
    }

    public JTextField getCtipo1() {
        return Ctipo1;
    }

    public void setCtipo1(JTextField Ctipo1) {
        this.Ctipo1 = Ctipo1;
    }

    public JTextField getCtipo8() {
        return Ctipo8;
    }

    public void setCtipo8(JTextField Ctipo8) {
        this.Ctipo8 = Ctipo8;
    }

    public JTextField getCtipo2() {
        return Ctipo2;
    }

    public void setCtipo2(JTextField Ctipo2) {
        this.Ctipo2 = Ctipo2;
    }

    public JTextField getCtipo3() {
        return Ctipo3;
    }

    public void setCtipo3(JTextField Ctipo3) {
        this.Ctipo3 = Ctipo3;
    }

    public JTextField getCtipo4() {
        return Ctipo4;
    }

    public void setCtipo4(JTextField Ctipo4) {
        this.Ctipo4 = Ctipo4;
    }

    public JTextField getCtipo5() {
        return Ctipo5;
    }

    public void setCtipo5(JTextField Ctipo5) {
        this.Ctipo5 = Ctipo5;
    }

    public JTextField getCtipo6() {
        return Ctipo6;
    }

    public void setCtipo6(JTextField Ctipo6) {
        this.Ctipo6 = Ctipo6;
    }

    public JTextField getCtipo7() {
        return Ctipo7;
    }

    public void setCtipo7(JTextField Ctipo7) {
        this.Ctipo7 = Ctipo7;
    }

    public JButton getBtnAnterior() {
        return btnAnterior;
    }

    public void setBtnAnterior(JButton btnAnterior) {
        this.btnAnterior = btnAnterior;
    }

    public JButton getBtnSiguiente() {
        return btnSiguiente;
    }

    public void setBtnSiguiente(JButton btnSiguiente) {
        this.btnSiguiente = btnSiguiente;
    }

    public JLabel getLblC1() {
        return lblC1;
    }

    public void setLblC1(JLabel lblC1) {
        this.lblC1 = lblC1;
    }

    public JLabel getLblC2() {
        return lblC2;
    }

    public void setLblC2(JLabel lblC2) {
        this.lblC2 = lblC2;
    }

    public JLabel getLblC3() {
        return lblC3;
    }

    public void setLblC3(JLabel lblC3) {
        this.lblC3 = lblC3;
    }

    public JLabel getLblC4() {
        return lblC4;
    }

    public void setLblC4(JLabel lblC4) {
        this.lblC4 = lblC4;
    }

    public JLabel getLblC5() {
        return lblC5;
    }

    public void setLblC5(JLabel lblC5) {
        this.lblC5 = lblC5;
    }

    public JLabel getLblC6() {
        return lblC6;
    }

    public void setLblC6(JLabel lblC6) {
        this.lblC6 = lblC6;
    }

    public JLabel getLblC7() {
        return lblC7;
    }

    public void setLblC7(JLabel lblC7) {
        this.lblC7 = lblC7;
    }

    public JLabel getLblC8() {
        return lblC8;
    }

    public void setLblC8(JLabel lblC8) {
        this.lblC8 = lblC8;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }

    public JPanel getPndC1() {
        return pndC1;
    }

    public void setPndC1(JPanel pndC1) {
        this.pndC1 = pndC1;
    }

    public JPanel getPndC2() {
        return pndC2;
    }

    public void setPndC2(JPanel pndC2) {
        this.pndC2 = pndC2;
    }

    public JPanel getPndC3() {
        return pndC3;
    }

    public void setPndC3(JPanel pndC3) {
        this.pndC3 = pndC3;
    }

    public JPanel getPndC4() {
        return pndC4;
    }

    public void setPndC4(JPanel pndC4) {
        this.pndC4 = pndC4;
    }

    public JPanel getPndC5() {
        return pndC5;
    }

    public void setPndC5(JPanel pndC5) {
        this.pndC5 = pndC5;
    }

    public JPanel getPndC6() {
        return pndC6;
    }

    public void setPndC6(JPanel pndC6) {
        this.pndC6 = pndC6;
    }

    public JPanel getPndC7() {
        return pndC7;
    }

    public void setPndC7(JPanel pndC7) {
        this.pndC7 = pndC7;
    }

    public JPanel getPndC8() {
        return pndC8;
    }

    public void setPndC8(JPanel pndC8) {
        this.pndC8 = pndC8;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getjPanel2() {
        return jPanel2;
    }

    public void setjPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public void setjPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public void setjPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JSeparator getjSeparator1() {
        return jSeparator1;
    }

    public void setjSeparator1(JSeparator jSeparator1) {
        this.jSeparator1 = jSeparator1;
    }

    public JLabel getLblElixir() {
        return lblElixir;
    }

    public void setLblElixir(JLabel lblElixir) {
        this.lblElixir = lblElixir;
    }

    public JLabel getLblUtilidad() {
        return lblUtilidad;
    }

    public void setLblUtilidad(JLabel lblUtilidad) {
        this.lblUtilidad = lblUtilidad;
    }


    public JLabel getLblVida() {
        return lblVida;
    }

    public void setLblVida(JLabel lblVida) {
        this.lblVida = lblVida;
    }

    public JProgressBar getPgrBarElixir() {
        return pgrBarElixir;
    }

    public void setPgrBarElixir(JProgressBar pgrBarElixir) {
        this.pgrBarElixir = pgrBarElixir;
    }

    public JProgressBar getPgrBarUtilidad() {
        return pgrBarUtilidad;
    }

    public void setPgrBarUtilidad(JProgressBar pgrBarUtilidad) {
        this.pgrBarUtilidad = pgrBarUtilidad;
    }
    

    public JProgressBar getPgrBarVida() {
        return pgrBarVida;
    }

    public void setPgrBarVida(JProgressBar pgrBarVida) {
        this.pgrBarVida = pgrBarVida;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ccalidad1;
    private javax.swing.JTextField Ccalidad2;
    private javax.swing.JTextField Ccalidad3;
    private javax.swing.JTextField Ccalidad4;
    private javax.swing.JTextField Ccalidad5;
    private javax.swing.JTextField Ccalidad6;
    private javax.swing.JTextField Ccalidad7;
    private javax.swing.JTextField Ccalidad8;
    private javax.swing.JTextField Cnombre1;
    private javax.swing.JTextField Cnombre2;
    private javax.swing.JTextField Cnombre3;
    private javax.swing.JTextField Cnombre4;
    private javax.swing.JTextField Cnombre5;
    private javax.swing.JTextField Cnombre6;
    private javax.swing.JTextField Cnombre7;
    private javax.swing.JTextField Cnombre8;
    private javax.swing.JTextField Ctipo1;
    private javax.swing.JTextField Ctipo2;
    private javax.swing.JTextField Ctipo3;
    private javax.swing.JTextField Ctipo4;
    private javax.swing.JTextField Ctipo5;
    private javax.swing.JTextField Ctipo6;
    private javax.swing.JTextField Ctipo7;
    private javax.swing.JTextField Ctipo8;
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblC1;
    private javax.swing.JLabel lblC2;
    private javax.swing.JLabel lblC3;
    private javax.swing.JLabel lblC4;
    private javax.swing.JLabel lblC5;
    private javax.swing.JLabel lblC6;
    private javax.swing.JLabel lblC7;
    private javax.swing.JLabel lblC8;
    private javax.swing.JLabel lblElixir;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUtilidad;
    private javax.swing.JLabel lblUtilidad2;
    private javax.swing.JLabel lblVida;
    private javax.swing.JProgressBar pgrBarElixir;
    private javax.swing.JProgressBar pgrBarUtilidad;
    private javax.swing.JProgressBar pgrBarUtilidad2;
    private javax.swing.JProgressBar pgrBarVida;
    private javax.swing.JPanel pndC1;
    private javax.swing.JPanel pndC2;
    private javax.swing.JPanel pndC3;
    private javax.swing.JPanel pndC4;
    private javax.swing.JPanel pndC5;
    private javax.swing.JPanel pndC6;
    private javax.swing.JPanel pndC7;
    private javax.swing.JPanel pndC8;
    // End of variables declaration//GEN-END:variables
}
