/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;

/**
 *
 * @author Sergio Cruz
 */
public class CrearMazo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearMazo
     */
    public CrearMazo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCarta1 = new javax.swing.JLabel();
        cmbCarta1 = new javax.swing.JComboBox<>();
        lblCarta2 = new javax.swing.JLabel();
        cmbCarta2 = new javax.swing.JComboBox<>();
        lblCarta3 = new javax.swing.JLabel();
        cmbCarta3 = new javax.swing.JComboBox<>();
        lblCarta4 = new javax.swing.JLabel();
        cmbCarta4 = new javax.swing.JComboBox<>();
        lblCarta5 = new javax.swing.JLabel();
        cmbCarta5 = new javax.swing.JComboBox<>();
        lblCarta6 = new javax.swing.JLabel();
        cmbCarta6 = new javax.swing.JComboBox<>();
        lblCarta7 = new javax.swing.JLabel();
        cmbCarta7 = new javax.swing.JComboBox<>();
        lblCarta8 = new javax.swing.JLabel();
        cmbCarta8 = new javax.swing.JComboBox<>();
        btnGuardarMazo = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        lblCarta1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        lblCarta1.setText("Carta 1");

        lblCarta2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        lblCarta2.setText("Carta 2");

        lblCarta3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        lblCarta3.setText("Carta 3");

        lblCarta4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        lblCarta4.setText("Carta 4");

        lblCarta5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        lblCarta5.setText("Carta 5");

        lblCarta6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        lblCarta6.setText("Carta 6");

        lblCarta7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        lblCarta7.setText("Carta 7");

        lblCarta8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        lblCarta8.setText("Carta 8");

        btnGuardarMazo.setText("Guardar Mazo");

        lblTitulo.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 24)); // NOI18N
        lblTitulo.setText("Crear Mazo");

        jLabel1.setText("No repitas Cartas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(btnGuardarMazo, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(60, 60, 60)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblCarta8)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCarta7)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCarta6)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCarta5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCarta4)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCarta3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCarta2)
                                            .addComponent(lblCarta1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmbCarta1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbCarta2, 0, 610, Short.MAX_VALUE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel1)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta1)
                    .addComponent(cmbCarta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta2)
                    .addComponent(cmbCarta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta3)
                    .addComponent(cmbCarta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta4)
                    .addComponent(cmbCarta4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta5)
                    .addComponent(cmbCarta5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta6)
                    .addComponent(cmbCarta6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta7)
                    .addComponent(cmbCarta7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarta8)
                    .addComponent(cmbCarta8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGuardarMazo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getBtnGuardarMazo() {
        return btnGuardarMazo;
    }

    public void setBtnGuardarMazo(JButton btnGuardarMazo) {
        this.btnGuardarMazo = btnGuardarMazo;
    }

    public JComboBox<String> getCmbCarta1() {
        return cmbCarta1;
    }

    public void setCmbCarta1(JComboBox<String> cmbCarta1) {
        this.cmbCarta1 = cmbCarta1;
    }

    public JComboBox<String> getCmbCarta2() {
        return cmbCarta2;
    }

    public void setCmbCarta2(JComboBox<String> cmbCarta2) {
        this.cmbCarta2 = cmbCarta2;
    }

    public JComboBox<String> getCmbCarta3() {
        return cmbCarta3;
    }

    public void setCmbCarta3(JComboBox<String> cmbCarta3) {
        this.cmbCarta3 = cmbCarta3;
    }

    public JComboBox<String> getCmbCarta4() {
        return cmbCarta4;
    }

    public void setCmbCarta4(JComboBox<String> cmbCarta4) {
        this.cmbCarta4 = cmbCarta4;
    }

    public JComboBox<String> getCmbCarta5() {
        return cmbCarta5;
    }

    public void setCmbCarta5(JComboBox<String> cmbCarta5) {
        this.cmbCarta5 = cmbCarta5;
    }

    public JComboBox<String> getCmbCarta6() {
        return cmbCarta6;
    }

    public void setCmbCarta6(JComboBox<String> cmbCarta6) {
        this.cmbCarta6 = cmbCarta6;
    }

    public JComboBox<String> getCmbCarta7() {
        return cmbCarta7;
    }

    public void setCmbCarta7(JComboBox<String> cmbCarta7) {
        this.cmbCarta7 = cmbCarta7;
    }

    public JComboBox<String> getCmbCarta8() {
        return cmbCarta8;
    }

    public void setCmbCarta8(JComboBox<String> cmbCarta8) {
        this.cmbCarta8 = cmbCarta8;
    }

    public JLabel getLblCarta1() {
        return lblCarta1;
    }

    public void setLblCarta1(JLabel lblCarta1) {
        this.lblCarta1 = lblCarta1;
    }

    public JLabel getLblCarta2() {
        return lblCarta2;
    }

    public void setLblCarta2(JLabel lblCarta2) {
        this.lblCarta2 = lblCarta2;
    }

    public JLabel getLblCarta3() {
        return lblCarta3;
    }

    public void setLblCarta3(JLabel lblCarta3) {
        this.lblCarta3 = lblCarta3;
    }

    public JLabel getLblCarta4() {
        return lblCarta4;
    }

    public void setLblCarta4(JLabel lblCarta4) {
        this.lblCarta4 = lblCarta4;
    }

    public JLabel getLblCarta5() {
        return lblCarta5;
    }

    public void setLblCarta5(JLabel lblCarta5) {
        this.lblCarta5 = lblCarta5;
    }

    public JLabel getLblCarta6() {
        return lblCarta6;
    }

    public void setLblCarta6(JLabel lblCarta6) {
        this.lblCarta6 = lblCarta6;
    }

    public JLabel getLblCarta7() {
        return lblCarta7;
    }

    public void setLblCarta7(JLabel lblCarta7) {
        this.lblCarta7 = lblCarta7;
    }

    public JLabel getLblCarta8() {
        return lblCarta8;
    }

    public void setLblCarta8(JLabel lblCarta8) {
        this.lblCarta8 = lblCarta8;
    }

    public JLabel getLblTitulo() {
        return lblTitulo;
    }

    public void setLblTitulo(JLabel lblTitulo) {
        this.lblTitulo = lblTitulo;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMazo;
    private javax.swing.JComboBox<String> cmbCarta1;
    private javax.swing.JComboBox<String> cmbCarta2;
    private javax.swing.JComboBox<String> cmbCarta3;
    private javax.swing.JComboBox<String> cmbCarta4;
    private javax.swing.JComboBox<String> cmbCarta5;
    private javax.swing.JComboBox<String> cmbCarta6;
    private javax.swing.JComboBox<String> cmbCarta7;
    private javax.swing.JComboBox<String> cmbCarta8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarta1;
    private javax.swing.JLabel lblCarta2;
    private javax.swing.JLabel lblCarta3;
    private javax.swing.JLabel lblCarta4;
    private javax.swing.JLabel lblCarta5;
    private javax.swing.JLabel lblCarta6;
    private javax.swing.JLabel lblCarta7;
    private javax.swing.JLabel lblCarta8;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
